apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-support-frontend
  labels:
    app: chatbot-support-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot-support-frontend
  template:
    metadata:
      labels:
        app: chatbot-support-frontend
    spec:
      containers:
      - name: chatbot-support-frontend
        image: 'gcr.io/ai-chatbot-support-444616/chatbot-support-frontend:v1'
        ports:
        - containerPort: 8080
