apiVersion: v1
kind: Service
metadata:
  name: chatbot-support-frontend
spec:
  selector:
    app: chatbot-support-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer