apiVersion: v1
kind: Service
metadata:
  name: chatbot-support-frontend-service-production
  lables:
    app: chatbot-support
    env: production
spec:
  selector:
    app: chatbot-support-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer